title: "Suinan Xiao"
description: "Personal Website"
url: "https://suinanthebug.github.io"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: "Suinan Xiao"
  avatar: "/assets/images/profile.jpg"
  bio: "I do cool science and code."

header_pages:
  - about.md
  - projects.md

# Optional
# include:
#   - resume.pdf
