title: "Suinan Xiao"
description: "Bioinformatics Researcher"
url: "" # Leave empty for local development

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: "Suinan Xiao"
  avatar: "/assets/images/profile.jpg"
  bio: "I am interested in using the power of data to solve biological problems."
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/SUINANTHEBUG"
    # Uncomment and update the following as needed:
    # - label: "LinkedIn"
    #   icon: "fab fa-linkedin"
    #   url: "https://linkedin.com/in/YOUR_USERNAME"
    # - label: "CV"
    #   icon: "fas fa-file"
    #   url: "/assets/files/suinan-cv.pdf"

header_pages:
  - about.md
  - projects.md
